### ISSUE TITLE
Gioui golang gui

### ISSUE THREAD

**Issue by gedw99** [openairplay/AirplayMirroringGo#1]
The gioui will probably be a lot better. Its 100% goang and compiles for Web, Desktop and Mobile !

You can run this to get a feel for it:

https://github.com/gioui/gio-example/tree/main/component

For Desktop just do ``` go run main.go ``` and it will run.

For Web and Mobile compile and packing you just use the gogui tool at https://github.com/gioui/gio/tree/main/cmd/gogio

I would be happy to help get this working in this repo as mirroring is a cool 😎 things with apple AirPlay

**Comment by gedw99** [comment]
GIOUI can also take screenshots btw.

**Comment by gedw99** [comment]
@dubo-dubon-duponey  

@AlbanSeurat 

let me know if you interested.  Happy to help get a GUI going for Mirroring.

**Comment by joseph-bing-han** [comment]
@gedw99 
I am interested in this, but my current job is a little bit busy. 
If possible, you can start this solution first. I will join during Christmas.
Thanks.

**Comment by gedw99** [comment]
I will start it . No worries

**Comment by gedw99** [comment]
Can you add some setup / usage notes to the reader ?

i just want to match how your using it . 

Also Mac OS now has airplay2 so easier to test it

**Comment by joseph-bing-han** [comment]
@gedw99 
I choose Fyne for refactoring GUI finally.
Please review latest source code of branch main.

**Comment by gedw99** [comment]
hey @joseph-bing-han 

Had a look but i have a few questions:

Your mirroring screen, not audio ?

**Comment by gedw99** [comment]
I can make a gio port later if needed too.

**Comment by joseph-bing-han** [comment]
Yes only capture screen and send over airplay.
Reason is that this tool is used for sharing screen to AppleTV on Linux in our meeting room .
Apple TV plays pictures so slowly that syncing audio doesn't make sense.

**Comment by gedw99** [comment]
@joseph-bing-han ok thanks for the confirmation.

You mentioned that Apple TV plays pictures slowly. Can you give me an idea of how slow ? 
Maybe you can make a video of it operating ..
